Algoritmo "Exercicio01"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : OSVALDO PROSPER OREB
// Descrição   :  Calcula o valor salarial acrescido de um aumento de 50%. 
// Autor(a)    : Adriano Alves
// Data atual  : 13/01/2026

Var
// Seção de Declarações das variáveis 
SALARIO, NOVOSAL: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
LEIA (SALARIO)
NOVOSAL<-SALARIO + SALARIO * PERCENTUAL
ESCREVAL (NOVOSAL)

Fimalgoritmo
