Algoritmo "CalculoDivisao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/01/2026
Var
// Seção de Declarações das variáveis 
a, b: inteiro
resultado: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

a <- 5
b <- 2

resultado <- a / b

escreval(resultado)


Fimalgoritmo