Algoritmo "Exercicio3"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : OSVALDO PROSPER OREB
// Descrição   : Permite calcular percentual de acrescimos ao Salario
// Data atual  : 14/01/2026
Var
// Seção de Declarações das variáveis
SALARIO, NOVOSAL: REAL

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
LEIA (SALARIO)
LEIA (PERCENTUAL)
NOVOSAL<-SALARIO + SALARIO * 0.5
ESCREVAL (NOVOSAL)

Fimalgoritmo