Algoritmo "Exercicio4"
// Disciplina   : [Linguagem e Lógica de Programação]
// Nivel: Operações e Expressões Alfanuméricas
// Professor   : OSVALDO PROSPER OREB
// Descrição   : operador da adição (+) para a concatenação de cadeias de caracteres.
// Autor(a)    : Adriano
// Data atual  : 14/01/2026
Var
// Seção de Declarações das variáveis
NOME: CARACTERE

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
LEIA (NOME)
NOME<- "Sr. " + NOME
ESCREVAL (NOME)

Fimalgoritmo

